#!/bin/bash

cd all
rm -r 0 0.* 1* 2* 3* 4* 5* 6* 7* 8* 9* processor* postProcessing log
rm -r constant/polyMesh constant/extendedFeatureEdgeMesh

cd ../body
rm -r 0 0.* 1* 2* 3* 4* 5* 6* 7* 8* 9* processor* postProcessing
rm -r constant/polyMesh constant/extendedFeatureEdgeMesh

cd ../leftWing
rm -r 0 0.* 1* 2* 3* 4* 5* 6* 7* 8* 9* processor* postProcessing
rm -r constant/polyMesh constant/extendedFeatureEdgeMesh

cd ../rightWing
rm -r 0 0.* 1* 2* 3* 4* 5* 6* 7* 8* 9* processor* postProcessing
rm -r constant/polyMesh constant/extendedFeatureEdgeMesh

#