#!/bin/bash

# transforming obj file
# surfaceTransformPoints -scale '(3.33333 3.33333 3.33333)' file.obj file.obj

# create meshes

cd leftWing
surfaceFeatureExtract
blockMesh
decomposePar
mpirun -np 8 snappyHexMesh -overwrite -parallel
reconstructParMesh -constant
# snappyHexMesh -overwrite

cd ../rightWing
surfaceFeatureExtract
blockMesh
decomposePar
mpirun -np 8 snappyHexMesh -overwrite -parallel
reconstructParMesh -constant
# snappyHexMesh -overwrite

cd ../body
surfaceFeatureExtract
blockMesh
decomposePar
mpirun -np 8 snappyHexMesh -overwrite -parallel
reconstructParMesh -constant
# snappyHexMesh -overwrite

cd ../all
blockMesh

mergeMeshes . ../leftWing -overwrite
mergeMeshes . ../rightWing -overwrite
mergeMeshes . ../body -overwrite

#To create zones for overset treatment
topoSet

#To create zones for prescribed motion
topoSet -dict system/topoSetDict_movingZone

#Restore time folder 0
rm -r 0
cp -r 0_org 0

#And assign zoneID for overset treatment
setFields
checkMesh

renumberMesh -overwrite

decomposePar
mpirun -np 64 overPimpleDyMFoam -parallel
reconstructPar
# overPimpleDyMFoam | tee log