#!/bin/bash

ssh occam@silicibacter.cs.hmc.edu

. /usr/lib/openfoam/openfoam2212/etc/bashrc

export MODEL=/research/occam/model

cd $MODEL/kinematics
python3 6dof.py 

# add value ^^^

cd $MODEL/all

# rm -r 0.* 1* 2* 3* 4* 5* 6* 7* 8* 9* processor* postProcessing

# rm -r 0
# cp -r 0_org 0

# #And assign zoneID for overset treatment
# setFields
# checkMesh

# renumberMesh -overwrite

rm -r 0.* 1* 2* 3* 4* 5* 6* 7* 8* 9* processor* postProcessing
decomposePar
foamJob -p overPimpleDyMFoam
# mpirun -np 64 overPimpleDyMFoam -parallel


reconstructPar
rm -r processor*


# ================================copy====================================
# scp -r <file or folder> occam@silicibacter.cs.hmc.edu:/research/occam/model